# Setup
title:               Deep Learning Bootcamp
tagline:             'By NTU Graduate Students'
description:         'Website for DL bootcamp'
url:                 https://alkaluqman.github.io/deeplearning-bootcamp
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alka
  giturl:            'https://github.com/alkaluqman/deeplearning-bootcamp/tree/main/notebooks'
  email:             alka.luqman@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
